### ISSUE TITLE
Add SameSite cookie parameter

### ISSUE THREAD

**Issue by chmike** [chmike/securecookie#11]
The SameSite cookie parameter allows to reduce the risk of CSRF attacks if the remote browser takes it in account.

**Comment by chmike** [comment]
This change is postponed until the SameSite cookie parameter is official. It is currently only a draft RFC.

**Comment by agentabstract** [comment]
Giving this a bump.  I'm getting console errors in firefox and I actually came to your page to check on this.  Love your package I'm using it at work.

**Comment by chmike** [comment]
Hello and thank you for the feedback on the package. I'll work on it as soon as possible.

**Comment by chmike** [comment]
The SameSite parameter has been added with the new release v1.3.0.

**Comment by agentabstract** [comment]
Thank you so much.  This is actually a big issue right now Chrome 84 is now
assuming all cookies are samesite lax,  which is sort of the end of third
party cookies.

**Comment by chmike** [comment]
If I understood correctly, you need to set SameSite to None to allow third party cookie. But this will only work if the Secure parameter is set to true. The cookie will thus be only returned to https requests.

**Comment by agentabstract** [comment]
Yeah.  For now.  By 2022 they’ll do away with none completely.  Lax means
the cookie can be read by the same root domain as the url in the browser
address bar, and strict means it has to be the same domain entirely.  I was
using third party cookies and JavaScript to do a simple oauth attempt if
users were logged in.  I’ve reworked my stuff to only use first party
cookies now. I don’t want to be fighting with google, Apple, and Mozilla.
