### ISSUE TITLE
Cookie Domain Should Allow Hyphens

### ISSUE THREAD

**Issue by blitzrk** [chmike/securecookie#13]
`func checkDomain` currently returns an "invalid character" error if any characters in the domain are not an ANSI letter, digit, or period. Hyphens should also be allowed in certain positions for domains such as `www.foo-bar.com`.

The func comment references [RFC 1034 Sec 3.5](https://tools.ietf.org/html/rfc1034#section-3.5). According to the RFC each label - the name portion between each period - (1) must begin with a letter, (2) must end with a letter or digit if at least 2 characters long, and (3) may contain a letter, digit, or hyphen for intermediate characters when at least 3 characters long.

I'm working on a patch right now for my own use and will submit a PR for consideration once complete. I don't see a `CONTRIBUTING.md` file. Are there any specific requirements besides updating the `TestCheckDomain` test?

**Comment by chmike** [comment]
Hello and thank you very much for your contribution to make this lackage better. How could I forget the dash ? 

Contribution is currently informal because it's a tiny project with only one PR so far, yours. 

I found another bug in isLetterOrDigit. The uppercase letter range is wrong. I'll fix that.

**Comment by chmike** [comment]
After reviewing your code I came up with the following pseudo code to check domain name validity that would be simpler and correct. Would you accept to implement and validate it with a few more tests ? I would then merge the PR. 

```go
switch {
case len(name) == 0 :
    return nil
case len(name) > 255 :
    // error: too long
}
var l int
for var i int; i < len(name); i++ {
    b := name[i]
    if b == "." {
        // check label validity
        switch {
        case i - l < 1 :
            // error: label starting with "." at offset i
        case i - l > 63 :
            // error: label name[l:i] too long
        case name[l] == "-":
            // error: label name[l:i] starting with hyphen
        case name[i-1] == "-":
            // error: label name[l:i] ending with hyphen
        }
        l == i + 1
        continue
    }
    // test label character validity, note: tests are ordered by decreasing validity frequency
    if !(b >= "a" && b <= "z" || b >= "0" && b <= "9" || b == ´-´ || b >= "A" && b <= "Z") {
        // error: invalid character at offset i 
        // Note: show the printable unicode character starting at byte offset i. 
        // Note: one printable character may be composed of multiple unicode code points.
    }
}
if l == len(name) {
    // error: ends with "."
}
if b := name[l]; b >= "0" && b <= "9" {
    // error: tld name[l:] starting with digit
}
return nil
```

**Comment by chmike** [comment]
Note that name labels are now allowed to start with a digit so that we can have sub-domain names containing an IP address. Disabiguation with an IPv4 address is done with the constrain that a TLD can start with a digit.

**Comment by blitzrk** [comment]
Absolutely, I'll incorporate those changes. I agree that it looks simpler and more correct. Multi-byte unicode codepoints won't begin with a byte representing an ASCII alphanumeric character, so there's no point using the utf8 library like I had. And it's not worth maintaining or depending on a list of valid gTLDs for the edge cases of invalid or misspelled TLDs (e.g. `.1com` or `.con`) so the developer will just have to be aware.
