### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by marcelloh** [chmike/securecookie#16]
so I have this:
```
	locCookie, err = securecookie.New("session", key, securecookie.Params{
		Path:     "/",         // cookie received only when URL starts with this path
		Domain:   "localhost", // cookie received only when URL domain matches this one
		MaxAge:   3600,        // cookie becomes invalid 3600 seconds after it is set
		HTTPOnly: true,        // disallow access by remote javascript code
	})

	if err != nil {
		println(err)
	}
```
and this shows me that error is 6?

Which I looked up and is caused by:
```
func New(name string, key []byte, p Params) (*Obj, error) {
	block, err := aes.NewCipher(key[len(key)/2:])
	if err != nil {
		return nil, err
	}
```
the aes.NewCipher(key[len(key)/2:]) returns the 6 as an error.
Any ideas in how to fix this?

**Comment by chmike** [comment]
Could you please provide the exact error message you get ? 

What value did you provide for `key` ? Did you generate the `key` with the function `GenerateRandomKey()` ?

**Comment by marcelloh** [comment]
Well I tried but it gave me an error when `i do like this:
```
var key []byte = securecookie.GenerateRandomKey()
```
Because GenerateRandomKey return 2 values, so the code must be old.

Let me rewrite it a bit.
```
key, err := securecookie.GenerateRandomKey()
```
works....

**Comment by marcelloh** [comment]
but I did fill the key with another slice of bytes and the error was there, so perhaps catch that somehow.
And... if it is needed to have that key, while just leave it out and generate it in the creation itself?

**Comment by chmike** [comment]
That key is a parameter that is used to encode and decode the secure cookie.

If you generate a new key every time you restart your program and re-instantiate the secure cookie object, you won’t be able to decode cookie previously saved with another key.

The way to use it is to generate the key once and save it in a secure place on the server (file with appropriate protections). You then load the key  and pass this value to the `New` method. This way, you’ll be able to decode secure cookies even after the program is restarted.

**Comment by marcelloh** [comment]
But I did exactly that. I have a secure key in my config file, which is generated and never changed, but somehow the block, err := aes.NewCipher(key[len(key)/2:]) got an error on that.
Perhaps the key needs to of a specified length?

**Comment by chmike** [comment]
Yes, of course, the key must have a specific length and it must be random bytes, not a string. The function `GenerateRandomKey` will ensure that the key has the correct length and contains random bytes.
