### ISSUE TITLE
invalid encoded cookie

### ISSUE THREAD

**Issue by tcastelly** [chmike/securecookie#18]
Hello,

I have a strange behavior when I'm trying to get the value of the cookie:
> invalid encoded cookie value (MAC mismatch)

The creation of the cookie:
```go
return securecookie.New("refresh_token", key, securecookie.Params{
    Path:     "/api/refresh",                        // accessCookie to be sent back only when URL starts with this path
    Domain:   globalConfig.Domain,                   // accessCookie to be sent back only when URL domain matches this one
    MaxAge:   int(REFRESH_TOKEN_DURATION.Seconds()), // accessCookie becomes invalid
    HTTPOnly: true,                                  // disallow access by remote javascript code
    Secure:   globalConfig.SecureCookie,             // accessCookie received with HTTP for testing purpose
    SameSite: securecookie.Lax,                      // cookie received with same or sub-domain names
  })
```
The `key` come from a docker swarm secret.

I have this error **only** when I release a new version of the project. If I remove the swarm stack and re-deploy the same version it works.

Maybe someone has an idea, I'm a bit lost.

Thank you very much.

**Comment by chmike** [comment]
Hello, thank you for using securecookie. 

Have you tried to check the cookie just after generating it ? 

Have you checked that the key you use for checking is exactly the same the one used to generate the sexure cookie ?

**Comment by tcastelly** [comment]
Thanks to you!

I'm sorry my swarm secret was loaded but not used. Instead I use a static key generate during the build.

I'm really sorry ...

**Comment by chmike** [comment]
No problem. I’m glad you solved your problem.
