### ISSUE TITLE
Crypto Go ：we are a research group to help developers build secure applications.

### ISSUE THREAD

**Issue by 1047261438** [chmike/securecookie#22]
Hi, we are a research group to help developers build secure applications. We designed a cryptographic misuse detector (i.e., CryptoGo) on Go language. We found your great public repository from Github, and several security issues detected by CryptoGo are shown in the following. 
Note that the cryptographic algorithms are categorized with two aspects: security strength and security vulnerability based on NIST Special Publication 800-57 and other public publications. Moreover, CryptoGo defined certain rules derived from the APIs of Go cryptographic library and other popular cryptographic misuse detectors. The specific security issues we found are as follows:
Location: securecookie.go:166; 
Broken rule: Constant key in AES;
 We wish the above security issues could truly help you to build a secure application. If you have any concern or suggestion, please feel free to contact us, we are looking forward to your reply. Thanks.

**Comment by chmike** [comment]
Hello and thank you very much for what you do and your contribution to the quality of securecookie.

I would be glad to change my code, but your message is not clear. What change would be required to pass your test ? 

Also, I would be happy to contact you, but you don't provide any contact reference. I thus can't contact you. 

I will not install and run your cryptoGo application on my computer. Sorry about that.

**Comment by 1047261438** [comment]
Hello,


&nbsp; &nbsp;Thank you for your feedback.&nbsp;
&nbsp; &nbsp; we are just a research group to help developers build secure applications. We designed a cryptographic misuse detector (i.e., CryptoGo) on Go language.&nbsp;

&nbsp; &nbsp; We found your great public repository from Github, and hope that the design basis of CryptoGo can help your development work.

&nbsp; &nbsp; The detection principle of CryptoGo are as follows: First, we categorized all the cryptographic algorithms with two aspects: security strength and security vulnerability based on NIST Special Publication 800-57 and other public publications.&nbsp;

&nbsp; &nbsp; The classification results are shown in the following table.






&nbsp; &nbsp; Second, CryptoGo defined 12 rules derived from the APIs of Go cryptographic library and other popular cryptographic misuse detectors.&nbsp;

&nbsp; &nbsp; The rules are shown in the following table.



&nbsp; &nbsp;We wish the above security suggests could truly help you to build secure applications.&nbsp;
&nbsp; &nbsp;If you have any concern or suggestion, please feel free to contact us, we are looking forward to your reply.







Thanks again.

&nbsp;

Sincerely,

CryptoGo Team.&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chmike/securecookie"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月29日(星期一) 下午3:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chmike/securecookie] Crypto Go ：we are a research group to help developers build secure applications. (Issue #22)





 
Hello and thank you very much for what you do and your contribution to the quality of securecookie.
 
I would be glad to change my code, but your message is not clear. What change would be required to pass your test ?
 
Also, I would be happy to contact you, but you don't provide any contact reference. I thus can't contact you.
 
I will not install and run your cryptoGo application on my computer. Sorry about that.

**Comment by chmike** [comment]
Unfortunately, your response is barely readable. I can't take it seriously. I'll leave you another chance. If you don't make a clear and readable statement of the problem you want to report, I will have to delete your issue. Sorry about that.
